application: i-am-ok
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  login: admin
  script: gaeunit.py

- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
#- url: /signup.html
#  script: main.py
#  login: required
#
#- url: /account.html
#  script: main.py
#  login: required
#
#- url: /settings.html
#  script: main.py
#  login: required

- url: /worker/
  script: worker.py
  
- url: .*
  script: main.py